steps:

- id: 'create ansible ssh identity and inventory'
  name: 'gcr.io/$PROJECT_ID/ansible'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "***********************************************************************"
      echo "Branch: $BRANCH_NAME Environment: ${_ENV}"
      echo "public SSH-Keys:"
      echo "$$SSH_KEYS"
      echo "***********************************************************************"
      echo "$$ANSIBLE_SSH_PRIVATE_KEY" > id_rsa
      chmod 400 id_rsa
  secretEnv: ['SSH_KEYS', 'ANSIBLE_SSH_PRIVATE_KEY']

# Deploy configurations
- id: 'ansible-playbook site.yml'
  name: 'gcr.io/$PROJECT_ID/ansible'
  entrypoint: '/usr/bin/ansible-playbook'
  args:
  - -i
  - ansible/inventories/${_ENV}/hosts
  - ansible/site.yml
  env:
  - ANSIBLE_CONFIG=ansible/ansible.cfg  
  
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/ssh_keys/versions/latest
    env: 'SSH_KEYS'  
  - versionName: projects/$PROJECT_ID/secrets/cloudflare_api_key/versions/latest
    env: 'CLOUDFLARE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/cloudflare_email/versions/latest
    env: 'CLOUDFLARE_EMAIL'
  - versionName: projects/$PROJECT_ID/secrets/ansible_ssh_private_key/versions/latest
    env: 'ANSIBLE_SSH_PRIVATE_KEY'

    